################################################
#                                              #
# Author: Dimiqhz                              #
# Started: 16 December, 2024                   #
# GitHub: https://github.com/Dimiqhz/VeeBot-VK #
#                                              #
################################################

# Do not touch this!
version: 0.1

# I want to collect some anonymized data about the use of my script if you don't want to send your statistics about the script
# You can set "false" for this option
stats: true

# You can use the types: longpoll, callback
# If you don't know what it does, I recommend you set Long Poll API (longpoll)
type: "longpoll"

# API VERSION
# You can use the specified API version, the default is 5.199
# DO NOT TOUCH THIS, IF YOU DON'T KNOW WHAT IT DOES
api_version: 5199

# API KEY (ONLY IF YOU USE THE LONG POLL API)
# To get your API KEY, follow the link: https://vk.com/[LINK TO YOUR COMMUNITY PAGE]?atc=api
# and create key LONG POLL 
api_key: ""

################################################################################
# YOU CAN'T USE THE CALLBACK API AT THE MOMENT, IT WILL BE IN THE NEXT UPDATE. #
################################################################################

# CALLBACK SERVER URL (ONLY IF YOU USE THE CALLBACK API)
#callback_url: ""

# CALLBACK SECRET KEY (ONLY IF YOU USE THE CALLBACK API)
#callback_secret: ""

####################
# DATABASE CONNECT #
####################

# You can use MYSQL, M2, SQLITE, POSTGRESQL as a system for storing user data, bans, and more.
type: mysql

# Enter "true" if your server uses an SSL CERTIFICATE
use_cert: false 

# Enter your credentials for your MYSQL or PostgreSQL if you entered "MYSQL" or "PostgreSQL" next to "type", for example "localhost".
host: ""
port: 3389
username: "your-user"
password: "your-password"

# Enter the path to the SSL certificate file if you entered "true" next to "use_cert".
cert: "/path/to/cert"
cert-pkey: "/path/to/privatekey"